services:
  db:
    container_name: news.db
    image: postgres:latest
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news
    volumes:
      - news.db.data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - news_project.db.host

  news:
    build: .
    container_name: news.server
    restart: always
    command: |
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: news
    ports:
      - "8000:8000"

volumes:
  news.db.data: ~

networks:
    default: ~
